In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Strings

In [2]:
'I love tennis'

'I love tennis'

In [3]:
'2.3'

'2.3'

In [4]:
'2.3' + 4

TypeError: must be str, not int

In [5]:
'2.3' * 4

'2.32.32.32.3'

In [6]:
'be' + 'happy'

'behappy'

In [7]:
str(2.3)

'2.3'

In [8]:
int('2.3')

ValueError: invalid literal for int() with base 10: '2.3'

In [9]:
float('2.3')

2.3

In [10]:
int('23') + float('2.3')

25.3

In [11]:
x = 12

In [12]:
int(str(x) + '0')

120

<br><br><br><br><br><br><br><br><br><br><br><br>

## Minard's map

In [13]:
minard = Table.read_table('minard.csv')

In [14]:
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [15]:
minard.num_columns

5

In [16]:
minard.num_rows

8

In [17]:
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [18]:
minard.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [19]:
minard.column(4)

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [20]:
initial_size = minard.column('Survivors').item(0)

In [21]:
initial_size

145000

In [22]:
percentage_surviving = minard.column('Survivors')/initial_size

In [23]:
percentage_surviving

array([1.        , 0.96551724, 0.87655172, 0.68965517, 0.37931034,
       0.16551724, 0.13793103, 0.08275862])

In [24]:
with_percentages = minard.with_column('Percent Surviving', percentage_surviving)

In [25]:
with_percentages

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

In [26]:
with_percentages.set_format('Percent Surviving', PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

<br><br><br><br><br><br><br><br><br><br><br><br>

## Lists

In [27]:
2

2

In [28]:
2.0

2.0

In [29]:
make_array(2, 3.0)

array([2., 3.])

In [30]:
make_array(2, 3.0).item(0)

2.0

In [31]:
make_array(2, 'three')

array(['2', 'three'], dtype='<U21')

In [32]:
make_array(2, 'three').item(0)

'2'

In [33]:
[2, 'three']

[2, 'three']

In [34]:
type([2, 'three'])

list

In [35]:
flowers = Table.read_table('flowers.csv')

In [36]:
flowers

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

In [37]:
my_favorite_flower = [5, 'morning glory', 'purple']

In [38]:
flowers.with_row(my_favorite_flower)

Petals | Name          | Color
8      | lotus         | pink
34     | sunflower     | yellow
5      | rose          | red
5      | morning glory | purple

## Table operations: Take

In [39]:
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [40]:
minard.take(0)

Longitude | Latitude | City     | Direction | Survivors
32        | 54.8     | Smolensk | Advance   | 145000

In [41]:
minard.take([0, 1, 2, 3])

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000

In [42]:
np.arange(0, 4)

array([0, 1, 2, 3])

In [43]:
minard.take(np.arange(0,4))

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000

<br><br><br><br><br><br><br><br><br><br><br><br>

## Table operations: where

In [44]:
# This table can be found online: https://www.statcrunch.com/app/index.php?dataid=1843341
nba = Table.read_table('nba_salaries.csv')

In [45]:
nba

PLAYER           | POSITION | TEAM          | 2015-2016 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [46]:
nba.sort('2015-2016 SALARY')

PLAYER                 | POSITION | TEAM                 | 2015-2016 SALARY
Thanasis Antetokounmpo | SF       | New York Knicks      | 0.030888
Jordan McRae           | SG       | Phoenix Suns         | 0.049709
Cory Jefferson         | PF       | Phoenix Suns         | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies    | 0.055722
Orlando Johnson        | SG       | Phoenix Suns         | 0.055722
Phil Pressey           | PG       | Phoenix Suns         | 0.055722
Keith Appling          | PG       | Orlando Magic        | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets       | 0.099418
Erick Green            | PG       | Utah Jazz            | 0.099418
Jeff Ayres             | PF       | Los Angeles Clippers | 0.111444
... (407 rows omitted)

In [47]:
nba = nba.relabeled('2015-2016 SALARY', 'SALARY')

In [48]:
nba.sort('SALARY')

PLAYER                 | POSITION | TEAM                 | SALARY
Thanasis Antetokounmpo | SF       | New York Knicks      | 0.030888
Jordan McRae           | SG       | Phoenix Suns         | 0.049709
Cory Jefferson         | PF       | Phoenix Suns         | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies    | 0.055722
Orlando Johnson        | SG       | Phoenix Suns         | 0.055722
Phil Pressey           | PG       | Phoenix Suns         | 0.055722
Keith Appling          | PG       | Orlando Magic        | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets       | 0.099418
Erick Green            | PG       | Utah Jazz            | 0.099418
Jeff Ayres             | PF       | Los Angeles Clippers | 0.111444
... (407 rows omitted)

In [49]:
nba.where('SALARY', are.above(10))

PLAYER         | POSITION | TEAM              | SALARY
Paul Millsap   | PF       | Atlanta Hawks     | 18.6717
Al Horford     | C        | Atlanta Hawks     | 12
Joe Johnson    | SF       | Brooklyn Nets     | 24.8949
Thaddeus Young | PF       | Brooklyn Nets     | 11.236
Al Jefferson   | C        | Charlotte Hornets | 13.5
Nicolas Batum  | SG       | Charlotte Hornets | 13.1253
Kemba Walker   | PG       | Charlotte Hornets | 12
Derrick Rose   | PG       | Chicago Bulls     | 20.0931
Jimmy Butler   | SG       | Chicago Bulls     | 16.4075
Joakim Noah    | C        | Chicago Bulls     | 13.4
... (59 rows omitted)

In [50]:
nba.where('SALARY', are.above(10)).sort('SALARY')

PLAYER          | POSITION | TEAM                 | SALARY
DeMar DeRozan   | SG       | Toronto Raptors      | 10.05
Gerald Wallace  | SF       | Philadelphia 76ers   | 10.1059
Luol Deng       | SF       | Miami Heat           | 10.1516
Monta Ellis     | SG       | Indiana Pacers       | 10.3
Wilson Chandler | SF       | Denver Nuggets       | 10.4494
Brendan Haywood | C        | Cleveland Cavaliers  | 10.5225
Jrue Holiday    | PG       | New Orleans Pelicans | 10.5955
Tyreke Evans    | SG       | New Orleans Pelicans | 10.7346
Marcin Gortat   | C        | Washington Wizards   | 11.2174
Thaddeus Young  | PF       | Brooklyn Nets        | 11.236
... (59 rows omitted)

In [51]:
nba.where('SALARY', are.between(10, 11))

PLAYER          | POSITION | TEAM                 | SALARY
Brendan Haywood | C        | Cleveland Cavaliers  | 10.5225
Wilson Chandler | SF       | Denver Nuggets       | 10.4494
Monta Ellis     | SG       | Indiana Pacers       | 10.3
Luol Deng       | SF       | Miami Heat           | 10.1516
Tyreke Evans    | SG       | New Orleans Pelicans | 10.7346
Jrue Holiday    | PG       | New Orleans Pelicans | 10.5955
Gerald Wallace  | SF       | Philadelphia 76ers   | 10.1059
Danny Green     | SG       | San Antonio Spurs    | 10
DeMar DeRozan   | SG       | Toronto Raptors      | 10.05

In [52]:
nba.where('TEAM', are.equal_to('Toronto Raptors'))

PLAYER            | POSITION | TEAM            | SALARY
DeMarre Carroll   | SF       | Toronto Raptors | 13.6
Kyle Lowry        | PG       | Toronto Raptors | 12
DeMar DeRozan     | SG       | Toronto Raptors | 10.05
Cory Joseph       | PG       | Toronto Raptors | 7
Patrick Patterson | PF       | Toronto Raptors | 6.26867
Jonas Valanciunas | C        | Toronto Raptors | 4.66048
Terrence Ross     | SF       | Toronto Raptors | 3.55392
Luis Scola        | PF       | Toronto Raptors | 2.9
Bismack Biyombo   | C        | Toronto Raptors | 2.814
Luke Ridnour      | PG       | Toronto Raptors | 2.75
... (7 rows omitted)

In [53]:
nba.where('TEAM', 'Toronto Raptors')

PLAYER            | POSITION | TEAM            | SALARY
DeMarre Carroll   | SF       | Toronto Raptors | 13.6
Kyle Lowry        | PG       | Toronto Raptors | 12
DeMar DeRozan     | SG       | Toronto Raptors | 10.05
Cory Joseph       | PG       | Toronto Raptors | 7
Patrick Patterson | PF       | Toronto Raptors | 6.26867
Jonas Valanciunas | C        | Toronto Raptors | 4.66048
Terrence Ross     | SF       | Toronto Raptors | 3.55392
Luis Scola        | PF       | Toronto Raptors | 2.9
Bismack Biyombo   | C        | Toronto Raptors | 2.814
Luke Ridnour      | PG       | Toronto Raptors | 2.75
... (7 rows omitted)

In [54]:
nba.where('TEAM', are.containing('Raptors'))

PLAYER            | POSITION | TEAM            | SALARY
DeMarre Carroll   | SF       | Toronto Raptors | 13.6
Kyle Lowry        | PG       | Toronto Raptors | 12
DeMar DeRozan     | SG       | Toronto Raptors | 10.05
Cory Joseph       | PG       | Toronto Raptors | 7
Patrick Patterson | PF       | Toronto Raptors | 6.26867
Jonas Valanciunas | C        | Toronto Raptors | 4.66048
Terrence Ross     | SF       | Toronto Raptors | 3.55392
Luis Scola        | PF       | Toronto Raptors | 2.9
Bismack Biyombo   | C        | Toronto Raptors | 2.814
Luke Ridnour      | PG       | Toronto Raptors | 2.75
... (7 rows omitted)

In [55]:
nba.where('PLAYER', are.equal_to('Stephen Curry'))

PLAYER        | POSITION | TEAM                  | SALARY
Stephen Curry | PG       | Golden State Warriors | 11.3708

In [56]:
nba.where('TEAM', are.equal_to('Golden State Warriors'))

PLAYER            | POSITION | TEAM                  | SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

In [57]:
nba.where('TEAM', are.equal_to('Golden State Warriors')).sort('SALARY', descending=True)

PLAYER            | POSITION | TEAM                  | SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

In [58]:
nba.where('SALARY', are.between(10, 12))

PLAYER          | POSITION | TEAM                  | SALARY
Thaddeus Young  | PF       | Brooklyn Nets         | 11.236
Brendan Haywood | C        | Cleveland Cavaliers   | 10.5225
Kenneth Faried  | PF       | Denver Nuggets        | 11.236
Wilson Chandler | SF       | Denver Nuggets        | 10.4494
Andre Iguodala  | SF       | Golden State Warriors | 11.7105
Stephen Curry   | PG       | Golden State Warriors | 11.3708
Monta Ellis     | SG       | Indiana Pacers        | 10.3
Luol Deng       | SF       | Miami Heat            | 10.1516
Tyreke Evans    | SG       | New Orleans Pelicans  | 10.7346
Jrue Holiday    | PG       | New Orleans Pelicans  | 10.5955
... (5 rows omitted)